mainprefix: "%"
defaultjoinmessage: "**{user} Joined Invited By {Inviter} (Invites: {inv})**"
defaultleavemessage: "**{user} Left, Invited by {inviter}**"
token: client.login(process.env.TOKEN);
color: "BLUE"
